### ISSUE TITLE
Реализовать сервис для процесса обучения

### ISSUE THREAD

**Issue by Relorer** [Relorer/Edokuri#26]

**Comment by Chursyatina** [comment]
![Image](https://user-images.githubusercontent.com/60659856/222893923-3b05f287-f62b-4d74-bc44-8504a1aa57c9.png)

**Comment by Chursyatina** [comment]
![Image](https://user-images.githubusercontent.com/60659856/222893937-5f2bad0f-8d38-4e61-acb5-9ae0df31d0f0.png)
