### ISSUE TITLE
разработать дизайн настроек ридера\

### ISSUE THREAD

**Issue by Relorer** [Relorer/Edokuri#47]

**Comment by Malina2906** [comment]
![Image](https://user-images.githubusercontent.com/125138400/230592452-ccc7d163-c902-410c-9de0-b7209a0ffeb9.png)



![Image](https://user-images.githubusercontent.com/125138400/230592472-a06705bf-af2a-4018-ad89-8caa696641a1.png)



![Image](https://user-images.githubusercontent.com/125138400/230592524-223add0a-d782-46c3-8644-7e37c2f01262.png)



![Image](https://user-images.githubusercontent.com/125138400/230592575-6c8aa09c-9e20-4871-b5e9-4bf33afadd2b.png)



![Image](https://user-images.githubusercontent.com/125138400/230592610-f2aa3f25-2c2b-4cd2-a7f4-d8c9ca0cb407.png)



![Image](https://user-images.githubusercontent.com/125138400/230592662-5185d2c5-2490-487e-bb90-d1e453562459.png)
