### ISSUE TITLE
issue - settings_controller.g.dart

### ISSUE THREAD

**Issue by burhanaksendir** [Relorer/Edokuri#95]
Hello,
I wanted to run the application. But there is an error in this picture. What should I do?

<img width="1053" alt="Ekran Resmi 2023-04-07 00 26 51" src="https://user-images.githubusercontent.com/8548639/230497168-c1a35686-ebd2-456e-a143-b7fbbc8a48bd.png">

**Comment by TheFRR** [comment]
Seems like you didn't make code generation. Check out our [wiki](https://github.com/Relorer/Edokuri/wiki/Startup#run-the-application).
Also you can download apk [here](https://github.com/Relorer/Edokuri/releases/tag/1.1.0).

**Comment by burhanaksendir** [comment]
Thank you. @TheFRR
